import express from "express";
import dotenv from "dotenv";
import Router from "./routes/routes.js";
import Connection from "./database/db.js";
import DefaultData from "./default.js";
import cors from "cors";
import User from "./model/user_schema.js";
import Admin from "./model/admin_schema.js";
import { saveAdmins } from "./controllers/admin_controller.js";
const app = express();
app.use(cors());
app.use(express.json({ extended: true }));
app.use(express.urlencoded({ extended: true }));
dotenv.config();
const PORT = process.env.PORT || 8001;
const username = process.env.DB_USERNAME;
const password = process.env.DB_PASSWORD;
app.use("/", Router);
Connection(username, password);
// console.log(.user.stats());

// saveAdmins();
// DefaultData();
app.listen(PORT, () => console.log(`Server is running at PORT ${PORT}`));
